spring:
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://localhost:5432/tdd"
    username: postgres
    password: password
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
  logging:
    level:
      liquibase: INFO