server:
  friendlyName: Test Server
spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default-schema: public
  test:
    database:
      replace: none
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
    contexts: test
logging:
  level:
    liquibase: INFO
